build:
  python:
    image: python:2.7
    commands:
      - XDG_CACHE_HOME=/drone/pip-cache pip install -r requirements.txt
      - make test
    environment:
      - DATABASE_URL=postgres://postgres:pa55word@127.0.0.1:5432/weardc
      - PORT=8000
      - BASE_DIR=/mnt/data
  js:
    image: node:6.9.1
    commands:
      - cd dashboard/static/dashboard
      - npm install
      - npm run prod

compose:
  db:
    image: postgres:9.5.3
    environment:
      - POSTGRES_PASSWORD=pa55word
      - POSTGRES_DB=weardc

cache:
  mount:
    - dashboard/static/dashboard/node_modules
    - /drone/pip-cache

publish:
  docker:
    registry: https://registry.sourcelair.com
    username: stolos
    password: $$SOURCELAIR_REGISTRY_PASSWORD
    repo: stolosd
    tag:
      - $$COMMIT
      - $$BRANCH
    when:
      branch: [master]
