pipeline:
  python:
    image: python:2.7
    commands:
      - pip install -r requirements.txt
      - make test
    environment:
      - DATABASE_URL=postgres://postgres:pa55word@127.0.0.1:5432/weardc
      - PORT=8000
      - BASE_DIR=/mnt/data

  js:
    image: node:6.9.1
    commands:
      - cd dashboard/static/dashboard
      - npm install
      - npm run prod

  publish:
    image: plugins/docker
    registry: https://registry.sourcelair.com
    username: stolos
    password: ${SOURCELAIR_REGISTRY_PASSWORD}
    repo: stolosd
    tag:
      - ${DRONE_COMMIT}
      - ${DRONE_BRANCH}
    when:
      branch: [master]

services:
  db:
    image: postgres:9.5.3
    environment:
      - POSTGRES_PASSWORD=pa55word
      - POSTGRES_DB=weardc
